# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjnE0S6FxxiIO2RZ7_N3XEwxd2jbAHkE
"""

def calculadora(num1, num2, operacao):
    if operacao == 1:
        resultado = num1 + num2
    elif operacao == 2:
        resultado = num1 - num2
    elif operacao == 3:
        resultado = num1 * num2
    elif operacao == 4:
        if num2 != 0:
            resultado = num1 / num2
        else:
            print("Erro!")
            return 0
    else:
        print("Operação inválida!")
        return 0

    return resultado

resultado = calculadora(5, 2, 3)

print("Resultado:", resultado)