# -*- coding: utf-8 -*-
"""ATIVIDADE5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjnE0S6FxxiIO2RZ7_N3XEwxd2jbAHkE
"""

def calculadora():
    while True:
        print("\nSelecione a operação:")
        print("1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        try:
            opcao = int(input("Digite o número da operação desejada: "))
        except ValueError:
            print("Por favor, insira um número válido.")
            continue

        if opcao == 0:
            print("Encerrando a calculadora. Adeus!")
            break
        elif opcao in {1, 2, 3, 4}:
            try:
                num1 = float(input("Digite o primeiro número: "))
                num2 = float(input("Digite o segundo número: "))
            except ValueError:
                print("Por favor, insira números válidos.")
                continue

            if opcao == 1:
                resultado = num1 + num2
                print("Resultado da Soma:", resultado)
            elif opcao == 2:
                resultado = num1 - num2
                print("Resultado da Subtração:", resultado)
            elif opcao == 3:
                resultado = num1 * num2
                print("Resultado da Multiplicação:", resultado)
            elif opcao == 4:
                resultado = num1 / num2 if num2 != 0 else 0
                print("Resultado da Divisão:", resultado)
        else:
            print("Essa opção não existe. Tente novamente.")

if __name__ == "__main__":
    calculadora()