# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjnE0S6FxxiIO2RZ7_N3XEwxd2jbAHkE
"""

for andar in range(20, 0, -1):
    if andar != 13:
        print(andar)
print()

andar = 20
while andar >= 1:
    if andar != 13:
        print(andar)
    andar -= 1